x-common-app-config: &common-app-config
  restart: unless-stopped

networks:
  default:

volumes:
  staticfiles:

services:
  db_recipes:
    <<: *common-app-config
    image: postgres:18.1-alpine3.22@sha256:270579ee277a572fa8cfdbaec0e1ff588bb7247da92d25165c7237c483e565d9
    volumes:
      - $DATADIR/tandoor/postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - default

  web_recipes:
    <<: *common-app-config
    image: vabene1111/recipes:2.5.3@sha256:7ce6534c9ab0e471fd0f08add67e871b9173fb580c2f86294c3ead025603a3d7
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - $DATADIR/tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    ports:
      - 127.0.0.1:8255:80
    networks:
      - default
