x-common-app-config: &common-app-config
  restart: unless-stopped

networks:
  default:

volumes:
  staticfiles:

services:
  db_recipes:
    <<: *common-app-config
    image: postgres:18.0-alpine3.22@sha256:48c8ad3a7284b82be4482a52076d47d879fd6fb084a1cbfccbd551f9331b0e40
    volumes:
      - $DATADIR/tandoor/postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - default

  web_recipes:
    <<: *common-app-config
    image: vabene1111/recipes:2.3.5@sha256:0f8d061895e9ba57a6d048d295af9d2fac1aa442a8d053d3d7f68ad78c4d1c17
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - $DATADIR/tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    ports:
      - 127.0.0.1:8255:80
    networks:
      - default
