networks:
  default:
    driver: bridge

services:
  mc:
    image: itzg/minecraft-server
    environment:
      TZ: $TZ
      TIME_ZONE: $TZ
      EULA: 'true'
      TYPE: 'PAPER'
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
    ports:
      - '25565:25565'
      - '19133:19132/udp'
    volumes:
      - '$DATADIR/minecraft-java/data:/data'
