networks:
  default:
    driver: bridge

services:
  bds:
    container_name: minecraft_bedrock
    image: itzg/minecraft-bedrock-server@sha256:d89b3615ad0e924bea42fb020970060e40e51ce12408d3acbd1ae55a5dbcd365
    environment:
      TZ: $TZ
      TIME_ZONE: $TZ
      EULA: 'TRUE'
    ports:
      - '19132:19132/udp'
    volumes:
      - '$DATADIR/minecraft-bedrock/data:/data'
    stdin_open: true
    tty: true
